FROM java:8-jre
WORKDIR /usr/lib
ADD ./target/musicmerviceconfigserver-0.0.1-SNAPSHOT.jar /usr/lib/musicmerviceconfigserver-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","musicmerviceconfigserver-0.0.1-SNAPSHOT.jar"]
